export const LOGIN = 'LOGIN';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const REGISTER_COMPANY = 'REGISTER_COMPANY';
export const SIGN_OUT = 'SIGN_OUT';
export const CURRENT_USER = 'CURRENT_USER';
export const LOGIN_COMPANY = 'LOGIN_COMPANY';
export const LOGIN_STUDENT = 'LOGIN_STUDENT';
